"""add jd and profile to interview session

Revision ID: c7a514dc7771
Revises: 
Create Date: 2026-05-03 10:50:49.881053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c7a514dc7771'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('interview_sessions', sa.Column('profile_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'profile_data')
    op.drop_column('interview_sessions', 'job_description')
    # ### end Alembic commands ###
