"""Initial schema

Revision ID: 4dbefbd3cae0
Revises: 
Create Date: 2026-06-07 12:09:22.245737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4dbefbd3cae0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.Enum('technical', 'behavioral', 'hr', name='sessiontype'), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('summary_report', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_order', sa.Text(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('profile_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_sessions_status', 'interview_sessions', ['status'], unique=False)
    op.create_index('idx_sessions_user_id', 'interview_sessions', ['user_id'], unique=False)
    op.create_table('question_bank',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('session_type', sa.Enum('technical', 'behavioral', 'hr', name='sessiontype'), nullable=False),
    sa.Column('follow_up_hint', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index('idx_qbank_category', 'question_bank', ['category'], unique=False)
    op.create_index('idx_qbank_difficulty', 'question_bank', ['difficulty'], unique=False)
    op.create_index('idx_qbank_session_type', 'question_bank', ['session_type'], unique=False)
    op.create_table('interview_responses',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('user_answer_text', sa.Text(), nullable=True),
    sa.Column('user_audio_s3_url', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('score_for_question', sa.Integer(), nullable=True),
    sa.Column('evaluation_breakdown', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.question_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index('idx_responses_session_id', 'interview_responses', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_responses_session_id', table_name='interview_responses')
    op.drop_table('interview_responses')
    op.drop_index('idx_qbank_session_type', table_name='question_bank')
    op.drop_index('idx_qbank_difficulty', table_name='question_bank')
    op.drop_index('idx_qbank_category', table_name='question_bank')
    op.drop_table('question_bank')
    op.drop_index('idx_sessions_user_id', table_name='interview_sessions')
    op.drop_index('idx_sessions_status', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
