"""sync_models

Revision ID: 91023f8b9c3a
Revises: 002
Create Date: 2026-05-08 20:48:55.464221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91023f8b9c3a'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # We only care about optimization_jobs in this service
    # Existing tables like 'resumes' are managed by the Profile Service
    
    op.add_column('optimization_jobs', sa.Column('profile_snapshot', sa.JSON(), nullable=True))
    op.alter_column('optimization_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('optimization_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    
    try:
        op.drop_constraint('optimization_jobs_resume_id_fkey', 'optimization_jobs', type_='foreignkey')
        op.drop_column('optimization_jobs', 'resume_id')
    except:
        pass
        
    try:
        op.drop_column('optimization_jobs', 'celery_task_id')
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('optimization_jobs', sa.Column('celery_task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('optimization_jobs', sa.Column('resume_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key('optimization_jobs_resume_id_fkey', 'optimization_jobs', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.alter_column('optimization_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('optimization_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('optimization_jobs', 'profile_snapshot')
    op.create_table('resumes',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('parsed_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'uploaded'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.VARCHAR(length=50), server_default=sa.text("'resume.tex'::character varying"), autoincrement=False, nullable=False),
    sa.Column('generated_pdf_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_resumes_user_id', 'resumes', ['user_id'], unique=False)
    op.create_table('ats_scores',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('jd_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('composite_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('keyword_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('semantic_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('format_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('keyword_matches', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('keyword_gaps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('section_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name='ats_scores_resume_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ats_scores_pkey')
    )
    op.create_index('ix_ats_scores_user_id', 'ats_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###
